"""add_opposition_search_query_subscription

Revision ID: 8ea3e1140795
Revises: 9f9cd1759abb
Create Date: 2026-05-26 18:23:11.744990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea3e1140795'
down_revision: Union[str, None] = '9f9cd1759abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('classes_json', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_created_at'), 'search_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_query_name'), 'search_queries', ['query_name'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('search_credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_email'), 'subscriptions', ['customer_email'], unique=False)
    op.create_table('opposition_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trademark_id', sa.Uuid(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('opposing_party', sa.String(length=255), nullable=True),
    sa.Column('opposing_counsel', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=True),
    sa.Column('hearing_date', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trademark_id'], ['trademarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opposition_cases_trademark_id'), 'opposition_cases', ['trademark_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opposition_cases_trademark_id'), table_name='opposition_cases')
    op.drop_table('opposition_cases')
    op.drop_index(op.f('ix_subscriptions_customer_email'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_search_queries_query_name'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_created_at'), table_name='search_queries')
    op.drop_table('search_queries')
    # ### end Alembic commands ###
