"""initial_schema

Revision ID: 9f9cd1759abb
Revises: 
Create Date: 2026-05-26 17:08:16.906450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9cd1759abb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trademarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('application_number', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trademarks_name'), 'trademarks', ['name'], unique=False)
    op.create_table('deadline_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trademark_id', sa.Uuid(), nullable=False),
    sa.Column('deadline_type', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trademark_id'], ['trademarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deadline_alerts_due_date'), 'deadline_alerts', ['due_date'], unique=False)
    op.create_index(op.f('ix_deadline_alerts_trademark_id'), 'deadline_alerts', ['trademark_id'], unique=False)
    op.create_table('trademark_classes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trademark_id', sa.Uuid(), nullable=False),
    sa.Column('nice_class_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trademark_id'], ['trademarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trademark_classes_trademark_id'), 'trademark_classes', ['trademark_id'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trademark_id', sa.Uuid(), nullable=False),
    sa.Column('conflicting_mark_name', sa.String(length=255), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trademark_id'], ['trademarks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_trademark_id'), 'watchlist_entries', ['trademark_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_trademark_id'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_trademark_classes_trademark_id'), table_name='trademark_classes')
    op.drop_table('trademark_classes')
    op.drop_index(op.f('ix_deadline_alerts_trademark_id'), table_name='deadline_alerts')
    op.drop_index(op.f('ix_deadline_alerts_due_date'), table_name='deadline_alerts')
    op.drop_table('deadline_alerts')
    op.drop_index(op.f('ix_trademarks_name'), table_name='trademarks')
    op.drop_table('trademarks')
    # ### end Alembic commands ###
